package com.jk.eis.commen.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEPOSITION".
 */
public class Deposition {
    @Override
    public String toString() {
        return "Deposition{" +
                "id=" + id +
                ", field_id=" + field_id +
                ", segment_id=" + segment_id +
                ", seg_count=" + seg_count +
                ", begin_date=" + begin_date +
                ", end_date=" + end_date +
                '}';
    }

    private Long id;
    private Long field_id;
    private Long segment_id;
    private Integer seg_count;
    private Integer begin_date;
    private Integer end_date;

    public Deposition() {
    }

    public Deposition(Long id) {
        this.id = id;
    }

    public Deposition(Long id, Long field_id, Long segment_id, Integer seg_count, Integer begin_date, Integer end_date) {
        this.id = id;
        this.field_id = field_id;
        this.segment_id = segment_id;
        this.seg_count = seg_count;
        this.begin_date = begin_date;
        this.end_date = end_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getField_id() {
        return field_id;
    }

    public void setField_id(Long field_id) {
        this.field_id = field_id;
    }

    public Long getSegment_id() {
        return segment_id;
    }

    public void setSegment_id(Long segment_id) {
        this.segment_id = segment_id;
    }

    public Integer getSeg_count() {
        return seg_count;
    }

    public void setSeg_count(Integer seg_count) {
        this.seg_count = seg_count;
    }

    public Integer getBegin_date() {
        return begin_date;
    }

    public void setBegin_date(Integer begin_date) {
        this.begin_date = begin_date;
    }

    public Integer getEnd_date() {
        return end_date;
    }

    public void setEnd_date(Integer end_date) {
        this.end_date = end_date;
    }

}
