package com.jk.eis.commen.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEG_TYPE".
 */
public class SegType {

    private Long id;
    /** Not-null value. */
    private String typeNum;
    private String description;

    public SegType() {
    }

    public SegType(Long id) {
        this.id = id;
    }

    public SegType(Long id, String typeNum, String description) {
        this.id = id;
        this.typeNum = typeNum;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTypeNum() {
        return typeNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTypeNum(String typeNum) {
        this.typeNum = typeNum;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
